indent_type = "Spaces"
indent_width = 4
column_width = 120
call_parentheses = "Always"
quote_style = "AutoPreferDouble"
collapse_simple_statement = "Never" # Never, FunctionOnly, ConditionalOnly, or Always
